(()=>{
'use strict';
const $=id=>document.getElementById(id), q=s=>[...document.querySelectorAll(s)];
const PROJECTS='scrollcraft-director-projects-v1', FPS='scrollcraft-director-fps-v1';
const grammars=[
{id:'filmic',name:'Filmic one-shot',jp:'映画のような一本道',fits:'単一の感情曲線で運ぶ商品・ローンチ',feels:'映画を自分で押し進める',leans:['scrub','pin','drift','kinetic'],bans:'visible sequence / hard cuts / multiple entry points'},
{id:'editorial',name:'Chaptered editorial',jp:'章立て編集記事',fits:'方法論・物語・研究など読み応えがある内容',feels:'ページをめくる',leans:['flow','reveal','parallax'],bans:'full-bleed scrub hero / magnetic CTA / centered hero copy'},
{id:'surface',name:'Live surface',jp:'製品そのものがページ',fits:'ソフトウェア・ツール・ダッシュボード',feels:'操作している',leans:['pin','count','pointer'],bans:'marketing chrome / scrub / kinetic headline'},
{id:'world',name:'Continuous world',jp:'ひとつながりの世界',fits:'場所・工程・地理に意味がある体験',feels:'一つの空間を移動する',leans:['worldflight','waypoints','copy windows'],bans:'section boundaries / acts / hard cuts'},
{id:'poster',name:'Typographic poster',jp:'文字が主役のポスター',fits:'強い言葉・宣言・ブランドメッセージ',feels:'大きさと余白で言葉が到着する',leans:['kinetic','pin','reveal','drift'],bans:'photographic ground / scrub / cards'},
{id:'gallery',name:'Gallery / catalog',jp:'歩けるコレクション',fits:'商品群・作品・素材・事例集',feels:'展示室を歩く',leans:['pan','reveal','tilt','count'],bans:'argument-shaped pinned type / hero claim / persuasive labels'},
{id:'split',name:'Split stage',jp:'二項対立の舞台',fits:'Before/After・手動/自動など比較が核',feels:'均衡が崩れ勝敗が決まる',leans:['pin','reveal','count'],bans:'full-bleed before resolve / centered copy / pan'},
{id:'cutlist',name:'Rhythmic cutlist',jp:'高速ハードカット',fits:'音楽・スポーツ・イベント・若年層ブランド',feels:'短いカットが脈打つ',leans:['flow','reveal','count'],bans:'pin / long dwell / slow easing'}
];
let chosen='editorial', scores=[], active='prompt', sigVariant=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const lines=s=>String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
const slug=s=>(s||'project').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'project';
const getJSON=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function data(){return {projectName:$('projectName').value.trim(),sourceUrl:$('sourceUrl').value.trim(),subject:$('subject').value.trim(),belief:$('belief').value.trim(),cta:$('cta').value.trim(),brandRules:$('brandRules').value.trim(),vibe:$('vibe').value.trim(),references:$('references').value.trim(),journeyRaw:$('journeyRaw').value.trim(),energy:$('energy').value.trim(),feelRaw:$('feelRaw').value.trim(),peak:$('peak').value.trim(),uniqueSeed:$('uniqueSeed').value.trim(),aesthetic:$('aesthetic').value,worldMode:$('worldMode').value,assets:q('#assetChecks input:checked').map(x=>x.value),grammar:chosen,signatureMove:$('signatureMove').value.trim()}}
function rank(d){return grammars.map(g=>{let n=45;const t=(d.subject+' '+d.vibe+' '+d.uniqueSeed).toLowerCase();if(d.worldMode==='continuous')n+=g.id==='world'?42:g.id==='filmic'?10:-4;if(d.worldMode==='scenes')n+=['editorial','cutlist','gallery'].includes(g.id)?12:0;if(/software|tool|app|dashboard|ソフト|ツール|アプリ/.test(t))n+=g.id==='surface'?35:0;if(/商品|portfolio|作品|catalog|product/.test(t))n+=g.id==='gallery'?22:0;if(/比較|before|after|手動|自動/.test(t))n+=g.id==='split'?28:0;if(/音楽|sport|event|street|若/.test(t))n+=g.id==='cutlist'?25:0;if(d.aesthetic==='editorial')n+=g.id==='editorial'?20:0;if(d.aesthetic==='brutalist'||d.aesthetic==='maximalist')n+=g.id==='poster'?12:g.id==='cutlist'?10:0;return {...g,score:Math.max(20,Math.min(96,n))}}).sort((a,b)=>b.score-a.score)}
function renderGrammars(r=rank(data())){const box=$('grammarGrid');box.innerHTML=r.map((g,i)=>`<article class="grammar-card ${g.id===chosen?'selected':''} ${i===0?'recommended':''}"><span class="rank">MATCH ${g.score}%</span><h3>${g.name}</h3><p><strong>${g.jp}</strong><br>${g.feels}</p><div class="grammar-meta">${g.leans.map(x=>`<span>${x}</span>`).join('')}</div><p>禁止: ${g.bans}</p><button class="secondary-btn compact" data-grammar="${g.id}" type="button">このGrammarを使う</button></article>`).join('');q('[data-grammar]').forEach(b=>b.onclick=()=>selectGrammar(b.dataset.grammar))}
function selectGrammar(id){chosen=id;renderGrammars();generateScore();updateOutputs()}
function generateScore(){const d=data(), js=lines(d.journeyRaw), fs=String(d.feelRaw||'期待 → 好奇心 → 驚き → 納得 → 決意').split(/→|>|,/).map(x=>x.trim()).filter(Boolean);const beats=js.length?js:['Recognition','Tension','Turn','Substance','Range','Commitment'];const g=grammars.find(x=>x.id===chosen);const devices=g.leans.length?g.leans:['reveal'];scores=beats.slice(0,9).map((b,i)=>({beat:b,feeling:fs[i%fs.length]||'期待',cause:b,device:devices[i%devices.length],span:(i===Math.min(beats.length-1,Math.max(0,Math.floor(beats.length*.65))))?'2.4vh':'1.4vh',peak:i===Math.min(beats.length-1,Math.max(0,Math.floor(beats.length*.65))) }));renderScore()}
function renderScore(){const body=$('scoreBody');body.innerHTML=scores.map((r,i)=>`<tr class="${r.peak?'peak-row':''}"><td><input data-i="${i}" data-k="beat" value="${esc(r.beat)}"></td><td><input data-i="${i}" data-k="feeling" value="${esc(r.feeling)}"></td><td><input data-i="${i}" data-k="cause" value="${esc(r.cause)}"></td><td><input data-i="${i}" data-k="device" value="${esc(r.device)}"></td><td><input data-i="${i}" data-k="span" value="${esc(r.span)}"></td></tr>`).join('');q('#scoreBody input').forEach(x=>x.oninput=()=>{scores[+x.dataset.i][x.dataset.k]=x.value;updateOutputs()});$('peakPreview').textContent=data().peak||scores.find(x=>x.peak)?.cause||'—'}
function signature(){const d=data(), base=d.uniqueSeed||d.peak||'訪問者の操作と内容が一体になる瞬間';const opts=[`${base}。スクロール位置に応じて画面内の意味そのものが変わり、装飾ではなく物語の転換点として機能する。`,`${base}を中心に、ポインタまたはスクロールで「見る側」が完成させる一回限りの相互作用にする。`,`${base}をページのPeakに固定し、その直前まで抑えた画面が一度だけ大きく構造変化する。`];return opts[sigVariant%opts.length]}
function updateSignature(force=false){if(force||!$('signatureMove').value.trim())$('signatureMove').value=signature();$('tellSentence').textContent=`「このサイト、${$('signatureMove').value.trim()||'___'}するやつ」`}
function fp(){const g=grammars.find(x=>x.id===chosen);const maps={filmic:['minimal fixed bar','full-bleed scrub hero','pinned CTA'],editorial:['folio margin','title page','colophon'],surface:['app chrome','live product state','actual input'],world:['waypoint map','world establishing position','arrival object CTA'],poster:['none/compositional','extreme-scale word','small underlined link'],gallery:['object index','object one','last object / inquiry label'],split:['divider chrome','50/50 split','collapse to winner'],cutlist:['loud full-width bar','one-screen cut','abrupt CTA cut']};const m=maps[g.id];return {grammar:g.name,nav:m[0],hero:m[1],actShape:scores.map(x=>x.device).join(' → '),close:m[2],signature:$('signatureMove').value.trim()||'未設定'}}
function evaluate(){const cur=fp(), saved=getJSON(FPS);$('fingerprintGrid').innerHTML=Object.entries(cur).map(([k,v])=>`<div class="fingerprint-item"><span>${k}</span><strong>${esc(v)}</strong></div>`).join('');if(!saved.length){$('gateStatus').textContent='比較対象なし';$('gateBadge').textContent='NEW';$('gateText').textContent='最初の設計です。保存すると次回から6軸で比較します。';return}const cmp=saved.map(x=>({x,n:Object.keys(cur).filter(k=>cur[k]!==x.fingerprint[k]).length})).sort((a,b)=>a.n-b.n)[0];$('gateStatus').textContent=cmp.n>=4?'PASS':'REVISE';$('gateBadge').textContent=`${cmp.n}/6`;$('gateText').textContent=`最も近い「${cmp.x.projectName}」との差は ${cmp.n}/6 軸です。${cmp.n>=4?'Gateを通過。':'4軸以上変えてください。'}`}
function brief(){const d=data(),g=grammars.find(x=>x.id===chosen);return `# BRIEF — ${d.projectName||'Untitled project'}\n\n## Project\n- What / who: ${d.subject||'未入力'}\n- Existing site: ${d.sourceUrl||'なし'}\n- Belief: ${d.belief||'未入力'}\n- CTA: ${d.cta||'未入力'}\n- Brand rules: ${d.brandRules||'未入力'}\n\n## Interview\n1. Vibe: ${d.vibe||'未入力'}\n   References: ${d.references||'未入力'}\n2. Journey:\n${(lines(d.journeyRaw).length?lines(d.journeyRaw):['未入力']).map(x=>`   - ${x}`).join('\n')}\n3. Energy: ${d.energy||'未入力'}\n4. Feelings: ${d.feelRaw||'未入力'}\n   Peak: ${d.peak||'未入力'}\n5. Unique seed: ${d.uniqueSeed||'未入力'}\n6. Aesthetic: ${d.aesthetic||'未入力'}\n7. World mode: ${d.worldMode||'未入力'}\n8. Assets: ${d.assets.join(', ')||'未入力'}\n\n## Page Grammar\n- ${g.name} / ${g.jp}\n- Fits: ${g.fits}\n- Scroll feels: ${g.feels}\n- Leans on: ${g.leans.join(', ')}\n- Forbids: ${g.bans}\n\n## Feeling Curve / Scroll Score\n| Beat | Feeling | Cause | Device | Span |\n|---|---|---|---|---|\n${scores.map(r=>`| ${r.beat} | ${r.feeling} | ${r.cause} | ${r.device} | ${r.span} |`).join('\n')}\n\n## Engineered Peak\n${d.peak||scores.find(x=>x.peak)?.cause||'未入力'}\n\n## Signature Move\n${d.signatureMove||'未入力'}\n\n## Fingerprint\n\`\`\`json\n${JSON.stringify(fp(),null,2)}\n\`\`\`\n`}
function prompt(){const d=data(),g=grammars.find(x=>x.id===chosen);return `Claude Codeで、以下の設計を使ってプレミアムなscroll-driven websiteを実装してください。\n\n【Scrollcraft】\n公式リポジトリ https://github.com/nateherkai/scroll-craft の現行README / SKILL.md / references を正本として確認してください。未導入なら現行手順で導入し、doctor / workspace の要件も確認してください。\n\n【既存サイト】\n${d.sourceUrl||'なし'}\nURLがある場合は公開情報を調査し、コピーではなくブランドを保った体験再設計を行ってください。\n\n【Project】\n名前: ${d.projectName||'未入力'}\n対象: ${d.subject||'未入力'}\n最後に信じてもらうこと: ${d.belief||'未入力'}\nCTA: ${d.cta||'未入力'}\nブランド必須条件: ${d.brandRules||'未入力'}\n\n【Page Grammar】\n${g.name} (${g.jp})\nFits: ${g.fits}\nScroll feel: ${g.feels}\nLeans on: ${g.leans.join(', ')}\nBans: ${g.bans}\n途中で別Grammarへ混ぜないでください。\n\n【Feeling Curve / Scroll Score】\n${scores.map((r,i)=>`${i+1}. ${r.beat} / feeling: ${r.feeling} / cause: ${r.cause} / device: ${r.device} / span: ${r.span}${r.peak?' ← PEAK':''}`).join('\n')}\n\n【Signature Move】\n${d.signatureMove||'未入力'}\n既存deviceのパラメータ変更だけで済ませず、このサイト固有のsemantic HTML/CSS/JSとして実装してください。\n\n【制作・検証】\n- Feeling Curveを先に守る。Peakは1つ。直前を静かにする。\n- 同じdevice familyを2回連続させない。Grammarの禁止事項を厳守。\n- fake dashboard / 架空実績 / テンプレ的feature-card反復を避ける。\n- semantic HTML、keyboard、focus、prefers-reduced-motion、iPhone縦画面を確認。\n- 既存素材を生成素材より優先。\n- dead scroll、cue opacity、contrast、video seek、full-scroll screenshotを検証。\n\n以下のBRIEF.mdを入力の正本にしてください。\n\n${brief()}`}
function updateOutputs(){const d=data();$('briefOutput').value=brief();$('promptOutput').value=prompt();$('jsonOutput').value=JSON.stringify({schemaVersion:1,app:'Scrollcraft Director',generatedAt:new Date().toISOString(),project:d,grammar:grammars.find(x=>x.id===chosen),feelingCurve:scores,signatureMove:d.signatureMove,fingerprint:fp()},null,2);$('peakPreview').textContent=d.peak||scores.find(x=>x.peak)?.cause||'—';$('tellSentence').textContent=`「このサイト、${d.signatureMove||'___'}するやつ」`;evaluate()}
function analyze(){const r=rank(data());chosen=data().grammar||r[0].id;renderGrammars(r);$('bestGrammarName').textContent=`${r.find(x=>x.id===chosen)?.name||r[0].name} · ${r.find(x=>x.id===chosen)?.score||r[0].score}%`;$('bestGrammarReason').textContent='入力した用途・世界のつながり方・美意識から、この構造が最も自然です。';updateSignature(true);generateScore();updateOutputs();toast('設計案を更新しました')}
function saveProject(){const d=data();if(!d.projectName){toast('プロジェクト名を入力してください');return}const a=getJSON(PROJECTS);a.unshift({id:slug(d.projectName)+'-'+Date.now(),projectName:d.projectName,savedAt:new Date().toISOString(),data:d,scores});localStorage.setItem(PROJECTS,JSON.stringify(a.slice(0,30)));renderProjects();toast('この端末に保存しました')}
function apply(d){['projectName','sourceUrl','subject','belief','cta','brandRules','vibe','references','journeyRaw','energy','feelRaw','peak','uniqueSeed','aesthetic','worldMode','signatureMove'].forEach(k=>{if($(k))$(k).value=d[k]||''});q('#assetChecks input').forEach(c=>c.checked=(d.assets||[]).includes(c.value));q('#aestheticChoices button').forEach(b=>b.classList.toggle('selected',b.dataset.value===d.aesthetic));q('#worldModeChoices button').forEach(b=>b.classList.toggle('selected',b.dataset.value===d.worldMode));chosen=d.grammar||chosen}
function renderProjects(){const a=getJSON(PROJECTS);$('projectList').innerHTML=a.length?a.map(x=>`<article class="project-card"><h3>${esc(x.projectName)}</h3><p>${new Date(x.savedAt).toLocaleString('ja-JP')}</p><div class="card-actions"><button data-load="${x.id}">開く</button><button data-del="${x.id}">削除</button></div></article>`).join(''):'<div class="project-card"><h3>まだ保存はありません</h3><p>上の「保存」を押すと再開できます。</p></div>';q('[data-load]').forEach(b=>b.onclick=()=>{const r=getJSON(PROJECTS).find(x=>x.id===b.dataset.load);if(r){apply(r.data);scores=r.scores||[];renderScore();renderGrammars();updateOutputs();scrollTo({top:0,behavior:'smooth'});toast('保存した設計を開きました')}});q('[data-del]').forEach(b=>b.onclick=()=>{localStorage.setItem(PROJECTS,JSON.stringify(getJSON(PROJECTS).filter(x=>x.id!==b.dataset.del)));renderProjects()})}
function saveFP(){const d=data();if(!d.projectName){toast('先にプロジェクト名を入力してください');return}const a=getJSON(FPS).filter(x=>x.projectName!==d.projectName);a.unshift({projectName:d.projectName,savedAt:new Date().toISOString(),fingerprint:fp()});localStorage.setItem(FPS,JSON.stringify(a.slice(0,50)));evaluate();renderFP();toast('Fingerprintを保存しました')}
function renderFP(){const a=getJSON(FPS);$('fingerprintList').innerHTML=a.length?a.map((x,i)=>`<div class="fp-row"><div><strong>${esc(x.projectName)}</strong><p>${new Date(x.savedAt).toLocaleString('ja-JP')} · ${esc(x.fingerprint.grammar)}</p></div><button data-fpdel="${i}">削除</button></div>`).join(''):'<p class="privacy-note">まだ保存されていません。</p>';q('[data-fpdel]').forEach(b=>b.onclick=()=>{const x=getJSON(FPS);x.splice(+b.dataset.fpdel,1);localStorage.setItem(FPS,JSON.stringify(x));renderFP();evaluate()})}
function dl(name,text,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type:type+';charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
async function copy(){const el=active==='brief'?$('briefOutput'):active==='json'?$('jsonOutput'):$('promptOutput');try{await navigator.clipboard.writeText(el.value)}catch{el.select();document.execCommand('copy')}toast('コピーしました')}
function sample(){apply({projectName:'Meguro High School Experience',sourceUrl:'https://www.metro.ed.jp/meguro-h/',subject:'高校受験を考えている中学生と保護者向けの学校紹介。',belief:'勉強と学校生活の両方に本気になれる。',cta:'学校見学会を予約する',brandRules:'公式情報・校章・実在写真を優先。架空数値は禁止。',vibe:'知的、透明感、静かな熱量、都会的、青春',references:'青春映画、学校案内写真集、建築雑誌',journeyRaw:'校門の前に立つ\n教室へ入る\n授業の密度を感じる\n放課後へ移る\n文化祭の熱気に包まれる\n進路の安心感を知る\n見学会を選ぶ',energy:'静 → 中 → 中 → 高 → 最高 → 静 → 決意',feelRaw:'期待 → 安心 → 集中 → 好奇心 → 高揚 → 納得 → 決意',peak:'文化祭の幕が開く瞬間、静けさから一気に熱気へ変わる',uniqueSeed:'同じ廊下を進むだけで窓の外の季節と学校行事が3年間分進む',aesthetic:'editorial',worldMode:'continuous',assets:['ロゴ','ブランドカラー','写真','原稿'],grammar:'world',signatureMove:''});analyze()}
function progress(){const ss=q('[data-section]'),y=scrollY+innerHeight*.35;let s=1;ss.forEach(x=>{if(x.offsetTop<=y)s=+x.dataset.section});q('#stepNav a').forEach(a=>a.classList.toggle('active',+a.dataset.step<=s));$('progressFill').style.width=((s-1)/5*100)+'%'}
function init(){renderGrammars();generateScore();updateSignature(true);updateOutputs();renderProjects();$('qualityChecks').innerHTML=['dead scroll','cue opacity','composited contrast','video decode / seek','full-scroll screenshots','desktop / iPhone portrait','prefers-reduced-motion','semantic HTML / keyboard'].map(x=>`<div class="qcheck">${x}</div>`).join('');$('energyPreset').onclick=e=>{const b=e.target.closest('button');if(b){$('energy').value=b.dataset.value;q('#energyPreset button').forEach(x=>x.classList.toggle('selected',x===b));updateOutputs()}};$('aestheticChoices').onclick=e=>{const b=e.target.closest('button');if(b){$('aesthetic').value=b.dataset.value;q('#aestheticChoices button').forEach(x=>x.classList.toggle('selected',x===b));updateOutputs()}};$('worldModeChoices').onclick=e=>{const b=e.target.closest('button');if(b){$('worldMode').value=b.dataset.value;q('#worldModeChoices button').forEach(x=>x.classList.toggle('selected',x===b));updateOutputs()}};$('analyzeBtn').onclick=analyze;$('regenerateSignatureBtn').onclick=()=>{sigVariant++;updateSignature(true);updateOutputs()};$('addBeatBtn').onclick=()=>{scores.push({beat:'New beat',feeling:'期待',cause:'画面で起きる変化',device:'reveal',span:'1.4vh',peak:false});renderScore();updateOutputs()};$('saveBtn').onclick=saveProject;$('saveFingerprintBtn').onclick=saveFP;$('viewFingerprintsBtn').onclick=()=>{renderFP();$('fingerprintDialog').showModal()};$('closeFingerprintDialog').onclick=()=>$('fingerprintDialog').close();$('refreshProjectsBtn').onclick=renderProjects;$('copyOutputBtn').onclick=copy;$('downloadBriefBtn').onclick=()=>dl(slug(data().projectName)+'-BRIEF.md',$('briefOutput').value,'text/markdown');$('downloadJsonBtn').onclick=()=>dl(slug(data().projectName)+'-design.json',$('jsonOutput').value,'application/json');$('loadSampleBtn').onclick=sample;$('newProjectBtn').onclick=()=>{if(confirm('入力中の内容を消しますか？'))location.reload()};q('.output-tabs button').forEach(b=>b.onclick=()=>{active=b.dataset.tab;q('.output-tabs button').forEach(x=>x.classList.toggle('active',x===b));q('.output-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===active))});q('input,textarea').forEach(x=>x.addEventListener('input',()=>{if(['journeyRaw','feelRaw','peak'].includes(x.id))generateScore();updateOutputs()}));q('#assetChecks input').forEach(x=>x.onchange=updateOutputs);addEventListener('scroll',progress,{passive:true});progress();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);
})();
